/**
 * CLI command: overstory hooks install|uninstall|status
 *
 * Manages orchestrator hooks in .claude/settings.local.json.
 * Hooks are sourced from .overstory/hooks.json (generated by overstory init).
 *
 * This keeps the canonical hook configuration in .overstory/ while placing
 * a minimal copy in .claude/ only when the user explicitly opts in.
 * Running `overstory init` alone does NOT modify .claude/ — the user must
 * run `overstory hooks install` as a separate step.
 */

import { mkdir, unlink } from "node:fs/promises";
import { join } from "node:path";
import { loadConfig } from "../config.ts";
import { ValidationError } from "../errors.ts";
import { isOverstoryCommand, mergeEventHooks, stripOverstoryCommands } from "../hooks/merge-utils.ts";

const HOOKS_HELP = `overstory hooks — Manage orchestrator hooks

Usage: overstory hooks <subcommand>

Subcommands:
  install                  Install orchestrator hooks to .claude/settings.local.json
  uninstall                Remove orchestrator hooks from .claude/settings.local.json
  status                   Check if hooks are installed

Options:
  --force                  Overwrite existing hooks in .claude/settings.local.json
  --merge                  Append overstory hooks alongside existing hooks (never removes non-overstory entries)
  --json                   Output as JSON
  --help, -h               Show this help

Hooks source: .overstory/hooks.json (generated by overstory init)
Hooks target: .claude/settings.local.json (read by Claude Code)`;

/**
 * Install orchestrator hooks from .overstory/hooks.json to .claude/settings.local.json.
 *
 * Reads the canonical hook config from .overstory/hooks.json and writes it to
 * .claude/settings.local.json where Claude Code discovers it. Preserves any
 * existing non-hooks keys in the target file.
 */
async function installHooks(args: string[]): Promise<void> {
	const force = args.includes("--force");
	const merge = args.includes("--merge");
	const cwd = process.cwd();
	const config = await loadConfig(cwd);
	const projectRoot = config.project.root;

	// Read source hooks from .overstory/hooks.json
	const sourcePath = join(projectRoot, ".overstory", "hooks.json");
	const sourceFile = Bun.file(sourcePath);
	if (!(await sourceFile.exists())) {
		throw new ValidationError("No hooks.json found in .overstory/. Run 'overstory init' first.", {
			field: "source",
		});
	}

	const sourceContent = await sourceFile.text();
	const sourceHooks = JSON.parse(sourceContent) as Record<string, unknown>;

	// Check target .claude/settings.local.json
	const targetDir = join(projectRoot, ".claude");
	const targetPath = join(targetDir, "settings.local.json");
	const targetFile = Bun.file(targetPath);

	let targetConfig: Record<string, unknown> = {};
	if (await targetFile.exists()) {
		const existingContent = await targetFile.text();
		const existing = JSON.parse(existingContent) as Record<string, unknown>;

		if (existing.hooks && !force && !merge) {
			process.stdout.write(
				"Hooks already present in .claude/settings.local.json\n" +
					"Use --force to overwrite or --merge to append alongside existing hooks.\n",
			);
			return;
		}

		// Preserve non-hooks keys (e.g., env settings)
		targetConfig = existing;

		if (merge && existing.hooks) {
			// Merge: append overstory hook entries per event key, preserving non-overstory entries
			const existingHooks = existing.hooks as Record<string, unknown[]>;
			const sourceEventHooks = (sourceHooks.hooks ?? {}) as Record<string, unknown[]>;
			const merged: Record<string, unknown[]> = { ...existingHooks };

			for (const eventKey of Object.keys(sourceEventHooks)) {
				const sourceEntries = sourceEventHooks[eventKey] ?? [];
				const targetEntries = merged[eventKey] ?? [];
				merged[eventKey] = mergeEventHooks(targetEntries, sourceEntries);
			}

			targetConfig.hooks = merged;

			await mkdir(targetDir, { recursive: true });
			await Bun.write(targetPath, `${JSON.stringify(targetConfig, null, "\t")}\n`);

			process.stdout.write("\u2713 Merged orchestrator hooks into .claude/settings.local.json\n");
			process.stdout.write("  Source: .overstory/hooks.json\n");
			return;
		}
	}

	// --merge with no existing hooks falls through to normal install below

	// Set hooks from source, preserve other keys
	targetConfig.hooks = sourceHooks.hooks;

	// Write
	await mkdir(targetDir, { recursive: true });
	await Bun.write(targetPath, `${JSON.stringify(targetConfig, null, "\t")}\n`);

	process.stdout.write("\u2713 Installed orchestrator hooks to .claude/settings.local.json\n");
	process.stdout.write("  Source: .overstory/hooks.json\n");
}

/**
 * Remove orchestrator hooks from .claude/settings.local.json.
 *
 * When hooks are mixed (overstory entries alongside non-overstory entries), only
 * removes entries whose command contains "overstory" or "mulch". Event arrays that
 * become empty after removal are dropped. If all hooks are removed and no other
 * settings exist, removes the file entirely.
 */
async function uninstallHooks(_args: string[]): Promise<void> {
	const cwd = process.cwd();
	const config = await loadConfig(cwd);
	const projectRoot = config.project.root;

	const targetPath = join(projectRoot, ".claude", "settings.local.json");
	const targetFile = Bun.file(targetPath);

	if (!(await targetFile.exists())) {
		process.stdout.write("No .claude/settings.local.json found \u2014 nothing to uninstall.\n");
		return;
	}

	const content = await targetFile.text();
	const parsed = JSON.parse(content) as Record<string, unknown>;

	if (!parsed.hooks) {
		process.stdout.write(
			"No hooks found in .claude/settings.local.json \u2014 nothing to uninstall.\n",
		);
		return;
	}

	const existingHooks = parsed.hooks as Record<string, unknown[]>;

	// Selectively strip overstory commands at the inner hook level, preserving custom commands
	// that may coexist in the same entry. Entries that become empty are dropped entirely.
	const filtered: Record<string, unknown[]> = {};
	for (const [eventKey, entries] of Object.entries(existingHooks)) {
		if (!Array.isArray(entries)) continue;
		const kept: unknown[] = [];
		for (const entry of entries) {
			const stripped = stripOverstoryCommands(entry);
			if (stripped !== null) kept.push(stripped);
		}
		if (kept.length > 0) {
			filtered[eventKey] = kept;
		}
	}

	// Determine whether any non-overstory hooks survived the filter
	const hasRemainingHooks = Object.keys(filtered).length > 0;
	const updatedHooks: Record<string, unknown[]> | null = hasRemainingHooks ? filtered : null;

	const { hooks: _hooks, ...rest } = parsed;

	if (updatedHooks !== null && Object.keys(updatedHooks).length > 0) {
		// Some non-overstory hooks remain — write back with filtered hooks
		const updated = { ...rest, hooks: updatedHooks };
		await Bun.write(targetPath, `${JSON.stringify(updated, null, "\t")}\n`);
		process.stdout.write(
			"\u2713 Removed overstory hooks from .claude/settings.local.json (preserved non-overstory hooks)\n",
		);
		return;
	}

	// All overstory hooks removed — remove hooks key entirely
	const remainingKeys = Object.keys(rest);
	if (remainingKeys.length === 0) {
		await unlink(targetPath);
		process.stdout.write("\u2713 Removed .claude/settings.local.json (was hooks-only)\n");
	} else {
		await Bun.write(targetPath, `${JSON.stringify(rest, null, "\t")}\n`);
		process.stdout.write(
			"\u2713 Removed hooks from .claude/settings.local.json (preserved other settings)\n",
		);
	}
}

/**
 * Show hooks installation status.
 */
async function statusHooks(args: string[]): Promise<void> {
	const json = args.includes("--json");
	const cwd = process.cwd();
	const config = await loadConfig(cwd);
	const projectRoot = config.project.root;

	const sourcePath = join(projectRoot, ".overstory", "hooks.json");
	const targetPath = join(projectRoot, ".claude", "settings.local.json");

	const sourceExists = await Bun.file(sourcePath).exists();
	const targetExists = await Bun.file(targetPath).exists();

	let installed = false;
	if (targetExists) {
		const content = await Bun.file(targetPath).text();
		const parsed = JSON.parse(content) as Record<string, unknown>;
		installed = !!parsed.hooks;
	}

	if (json) {
		process.stdout.write(`${JSON.stringify({ sourceExists, installed })}\n`);
	} else {
		process.stdout.write(
			`Hooks source (.overstory/hooks.json): ${sourceExists ? "present" : "missing"}\n`,
		);
		process.stdout.write(
			`Hooks installed (.claude/settings.local.json): ${installed ? "yes" : "no"}\n`,
		);
		if (!installed && sourceExists) {
			process.stdout.write(`\nRun 'overstory hooks install' to install.\n`);
		}
	}
}

/**
 * Entry point for `overstory hooks <subcommand>`.
 */
export async function hooksCommand(args: string[]): Promise<void> {
	if (args.includes("--help") || args.includes("-h") || args.length === 0) {
		process.stdout.write(`${HOOKS_HELP}\n`);
		return;
	}

	const subcommand = args[0];
	const subArgs = args.slice(1);

	switch (subcommand) {
		case "install":
			await installHooks(subArgs);
			break;
		case "uninstall":
			await uninstallHooks(subArgs);
			break;
		case "status":
			await statusHooks(subArgs);
			break;
		default:
			throw new ValidationError(
				`Unknown hooks subcommand: ${subcommand}. Run 'overstory hooks --help' for usage.`,
				{ field: "subcommand", value: subcommand },
			);
	}
}
