import { describe, expect, test } from "bun:test";
import {
	generateOpenCodeGuardPlugin,
	generateOpenCodePermissionConfig,
} from "./opencode-guards.ts";
import type { HooksDef } from "./types.ts";

// Helper to build a HooksDef for testing.
function makeHooks(
	capability: string,
	agentName = "test-agent",
	worktreePath = "/tmp/worktree",
): HooksDef {
	return { agentName, capability, worktreePath };
}

describe("generateOpenCodeGuardPlugin", () => {
	describe("header and metadata", () => {
		test("contains generated-by comment", () => {
			const code = generateOpenCodeGuardPlugin(makeHooks("builder"));
			expect(code).toContain("Generated by overstory");
			expect(code).toContain("do not edit manually");
		});

		test("contains agent name and capability in header", () => {
			const code = generateOpenCodeGuardPlugin(makeHooks("scout", "my-scout"));
			expect(code).toContain("Agent: my-scout");
			expect(code).toContain("Capability: scout");
		});

		test("embeds agent name as constant", () => {
			const code = generateOpenCodeGuardPlugin(makeHooks("builder", "builder-alpha"));
			expect(code).toContain('const AGENT_NAME = "builder-alpha"');
		});

		test("embeds worktree path as constant", () => {
			const code = generateOpenCodeGuardPlugin(makeHooks("builder", "test", "/my/worktree/path"));
			expect(code).toContain('const WORKTREE_PATH = "/my/worktree/path"');
		});
	});

	describe("OpenCode plugin structure", () => {
		test("exports OverstoryGuard async function", () => {
			const code = generateOpenCodeGuardPlugin(makeHooks("builder"));
			expect(code).toContain("export const OverstoryGuard = async (");
		});

		test("contains tool.execute.before hook", () => {
			const code = generateOpenCodeGuardPlugin(makeHooks("builder"));
			expect(code).toContain('"tool.execute.before"');
		});

		test("contains tool.execute.after hook for activity tracking", () => {
			const code = generateOpenCodeGuardPlugin(makeHooks("builder"));
			expect(code).toContain('"tool.execute.after"');
			expect(code).toContain("ov log tool-end");
		});

		test("tool.execute.after references agent name", () => {
			const code = generateOpenCodeGuardPlugin(makeHooks("builder", "build-x"));
			expect(code).toContain("AGENT_NAME");
		});

		test("uses throw Error for blocking (not return { block: true })", () => {
			const code = generateOpenCodeGuardPlugin(makeHooks("scout"));
			expect(code).toContain("throw new Error(");
			expect(code).not.toContain("block: true");
		});
	});

	describe("non-implementation capabilities (scout, reviewer, lead)", () => {
		for (const capability of [
			"scout",
			"reviewer",
			"lead",
			"coordinator",
			"supervisor",
			"monitor",
		]) {
			test(`${capability}: blocks write tools`, () => {
				const code = generateOpenCodeGuardPlugin(makeHooks(capability));
				expect(code).toContain("WRITE_BLOCKED");
				expect(code).toContain(`${capability} agents cannot modify files`);
			});

			test(`${capability}: has dangerous bash pattern blocklist`, () => {
				const code = generateOpenCodeGuardPlugin(makeHooks(capability));
				expect(code).toContain("DANGEROUS_PATTERNS");
			});

			test(`${capability}: has safe prefix whitelist`, () => {
				const code = generateOpenCodeGuardPlugin(makeHooks(capability));
				expect(code).toContain("SAFE_PREFIXES");
			});
		}

		test("WRITE_BLOCKED includes lowercase 'edit' and 'write' (OpenCode tool names)", () => {
			const code = generateOpenCodeGuardPlugin(makeHooks("scout"));
			// Match inside the Set literal
			expect(code).toContain('"edit"');
			expect(code).toContain('"write"');
		});

		test("WRITE_BLOCKED also includes Claude Code tool names for forward compat", () => {
			const code = generateOpenCodeGuardPlugin(makeHooks("scout"));
			expect(code).toContain('"Write"');
			expect(code).toContain('"Edit"');
			expect(code).toContain('"NotebookEdit"');
		});
	});

	describe("coordination capabilities (coordinator, orchestrator, supervisor, monitor)", () => {
		for (const capability of ["coordinator", "orchestrator", "supervisor", "monitor"]) {
			test(`${capability}: git add whitelisted in safe prefixes`, () => {
				const code = generateOpenCodeGuardPlugin(makeHooks(capability));
				expect(code).toContain('"git add"');
				expect(code).toContain('"git commit"');
			});
		}

		test("non-coordination (scout) does NOT whitelist git add/commit", () => {
			const code = generateOpenCodeGuardPlugin(makeHooks("scout"));
			// git add/commit should NOT be in safe prefixes for scout
			const safePrefixSection =
				code.split("SAFE_PREFIXES")[1]?.split("DANGEROUS_PATTERNS")[0] ?? "";
			expect(safePrefixSection).not.toContain('"git add"');
			expect(safePrefixSection).not.toContain('"git commit"');
		});
	});

	describe("implementation capabilities (builder, merger)", () => {
		for (const capability of ["builder", "merger"]) {
			test(`${capability}: does NOT have WRITE_BLOCKED set`, () => {
				const code = generateOpenCodeGuardPlugin(makeHooks(capability));
				expect(code).not.toContain("WRITE_BLOCKED");
			});

			test(`${capability}: has file-modifying bash path boundary`, () => {
				const code = generateOpenCodeGuardPlugin(makeHooks(capability));
				expect(code).toContain("FILE_MODIFYING_PATTERNS");
				expect(code).toContain("Bash path boundary violation");
			});
		}
	});

	describe("universal guards (all capabilities)", () => {
		for (const capability of ["builder", "scout", "reviewer", "lead", "coordinator"]) {
			test(`${capability}: blocks git push`, () => {
				const code = generateOpenCodeGuardPlugin(makeHooks(capability));
				expect(code).toContain("git push is blocked");
			});

			test(`${capability}: blocks git reset --hard`, () => {
				const code = generateOpenCodeGuardPlugin(makeHooks(capability));
				expect(code).toContain("git reset --hard is not allowed");
			});

			test(`${capability}: enforces branch naming convention`, () => {
				const code = generateOpenCodeGuardPlugin(makeHooks(capability));
				expect(code).toContain("Branch must follow overstory/");
			});

			test(`${capability}: enforces path boundary on write/edit tools`, () => {
				const code = generateOpenCodeGuardPlugin(makeHooks(capability));
				expect(code).toContain("WRITE_SCOPE_TOOLS");
				expect(code).toContain("Path boundary violation");
			});
		}
	});

	describe("quality gates", () => {
		test("custom quality gates appear as safe prefixes", () => {
			const code = generateOpenCodeGuardPlugin({
				agentName: "test",
				capability: "scout",
				worktreePath: "/tmp/wt",
				qualityGates: [
					{ name: "Tests", command: "pytest", description: "run tests" },
					{ name: "Lint", command: "ruff check", description: "lint" },
				],
			});
			expect(code).toContain('"pytest"');
			expect(code).toContain('"ruff check"');
		});

		test("default quality gates included when qualityGates not provided", () => {
			const code = generateOpenCodeGuardPlugin(makeHooks("scout"));
			expect(code).toContain('"bun test"');
			expect(code).toContain('"bun run lint"');
			expect(code).toContain('"bun run typecheck"');
		});
	});
});

describe("generateOpenCodePermissionConfig", () => {
	describe("non-implementation capabilities", () => {
		for (const capability of ["scout", "reviewer", "lead", "coordinator"]) {
			test(`${capability}: denies edit and write`, () => {
				const config = generateOpenCodePermissionConfig(capability);
				const permission = config.permission as Record<string, unknown>;
				expect(permission.edit).toBe("deny");
				expect(permission.write).toBe("deny");
			});

			test(`${capability}: restricts bash with safe commands allowed`, () => {
				const config = generateOpenCodePermissionConfig(capability);
				const permission = config.permission as Record<string, unknown>;
				const bash = permission.bash as Record<string, string>;
				expect(bash["*"]).toBe("ask");
				expect(bash["git status *"]).toBe("allow");
				expect(bash["git log *"]).toBe("allow");
				expect(bash["git push *"]).toBe("deny");
			});

			test(`${capability}: allows ov CLI commands`, () => {
				const config = generateOpenCodePermissionConfig(capability);
				const permission = config.permission as Record<string, unknown>;
				const bash = permission.bash as Record<string, string>;
				expect(bash["ov *"]).toBe("allow");
				expect(bash["sd *"]).toBe("allow");
			});
		}
	});

	describe("implementation capabilities", () => {
		for (const capability of ["builder", "merger"]) {
			test(`${capability}: allows most tools`, () => {
				const config = generateOpenCodePermissionConfig(capability);
				const permission = config.permission as Record<string, unknown>;
				expect(permission["*"]).toBe("allow");
			});

			test(`${capability}: still denies git push via bash`, () => {
				const config = generateOpenCodePermissionConfig(capability);
				const permission = config.permission as Record<string, unknown>;
				const bash = permission.bash as Record<string, string>;
				expect(bash["git push *"]).toBe("deny");
				expect(bash["git reset --hard *"]).toBe("deny");
			});
		}
	});

	describe("config structure", () => {
		test("includes $schema", () => {
			const config = generateOpenCodePermissionConfig("builder");
			expect(config.$schema).toBe("https://opencode.ai/config.json");
		});

		test("disables snapshot for agents", () => {
			const config = generateOpenCodePermissionConfig("scout");
			expect(config.snapshot).toBe(false);
		});
	});
});
